// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using QlikBar.SDK.DTOs;

namespace QlikBar.SDK.DotNet40.Domain.Model
{

    public class Order : IEntity
    {

        public int Id { get; set; }

        public Article Article { get; set; }

        public decimal Price { get; set; }

        public int Status { get; set; }

        public int Quantity { get; set; }

        public string Comments { get; set; }
     
        public OrderPart[] Parts { get; set; }

        public override string ToString() { return Id.ToString(); }
    }

}
