// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace QlikBar.SDK.DotNet40.Domain.Model
{

    public class OrderPart
    {

        public int Id { get; set; }

        public Article Article { get; set; }

        public override string ToString() { return Id + " - " + Article; }
    }

}
