// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;


namespace QlikBar.SDK.DTOs
{

    public class Article
    {
        [JsonProperty("parent")]
        public int Parent { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("remoteId")]
        public string RemoteId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("deleted")]
        public bool Deleted { get; set; }

        [JsonProperty("visibility")]
        public int Visibility { get; set; }

        [JsonProperty("price")]
        public decimal Price { get; set; }

        [JsonProperty("parts")]
        public ComboPart[] Parts { get; set; }

        public override string ToString() { return Id + " - " + Name; }
    }

}
