// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace QlikBar.SDK.DTOs
{

    public class Candidate
    {
        [JsonProperty("id")]
        public int Id { get; set; }
    
        [JsonProperty("article")]
        public int Article { get; set; }

        [JsonProperty("price")]
        public decimal Price { get; set; }

        public override string ToString() { return Article.ToString(); }
    }

}
