// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using QlikBar.SDK;

namespace QlikBar.SDK.DTOs
{

    public class CheckIn
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("role")]
        public int Role { get; set; }

        [JsonProperty("owner")]
        public Client Owner { get; set; }

        [JsonProperty("orders")]
        public Order[] Orders { get; set; }

        public override string ToString() { return Id.ToString(); }
    }

}
