// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;

namespace QlikBar.SDK.DTOs
{

    public class Table
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("tariff")]
        public int Tariff { get; set; }

        [JsonProperty("enabled")]
        public bool Enabled { get; set; }

        [JsonProperty("remoteId")]
        public string RemoteId { get; set; }

        [JsonProperty("qr")]
        public string Qr { get; set; }

        [JsonProperty("askedForBill")]
        public bool AskedForBill { get; set; }

        [JsonProperty("summonedServer")]
        public bool SummonedServer { get; set; }

        [JsonProperty("checkIns")]
        public CheckIn[] CheckIns { get; set; }

  
        public override string ToString() { return Id + " - " + Name; }
    }

}
